(()=>{
'use strict';
const D=window.CHRONOS_DATA;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store={get(k,d=null){try{return localStorage.getItem(k)??d}catch{return d}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
let lang=store.get('chronos-lang','ja'), theme=store.get('chronos-theme','dark'), depth=store.get('chronos-depth','auto');
let currentPointId=store.get('chronos-point','atlantic1492'), currentEventId='french-revolution', timelineFilter='all', libraryFilter='all';
let worldLand=null, scrollRAF=0; const scrollMemory={};
const laneY=[110,245,380,515], laneNames={ja:['人類・環境','政治・帝国','思想・宗教','技術・経済'],ru:['Люди и среда','Политика и империи','Идеи и религии','Технологии и экономика']};
const t=k=>D.UI[lang][k]||D.UI.ja[k]||k, l=v=>v&&typeof v==='object'&&!Array.isArray(v)?(v[lang]??v.ja??''):v;
const byPoint=id=>D.TIMEPOINTS.find(p=>p.id===id), byEvent=id=>D.EVENTS[id], eventForPoint=id=>Object.entries(D.EVENTS).find(([,e])=>e.point===id)?.[0]||id;
function genericEvent(id){
 if(id==='prehuman')return {kind:{ja:'地球史への入口',ru:'Вход в историю Земли'},title:{ja:'人類以前の世界',ru:'Мир до появления людей'},period:'46億年前 → 約30万年前',region:{ja:'地球',ru:'Земля'},point:'sapiens',lead:{ja:'CHRONOSの本編はホモ・サピエンスから始まりますが、その前提となった生命・気候・地質の歴史へここから遡れます。',ru:'Основной CHRONOS начинается с Homo sapiens, но отсюда можно уйти глубже — к жизни, климату и геологии Земли.'},storyHeadline:{ja:'人類史の前提は、人類よりはるか以前に作られた',ru:'Условия человеческой истории возникли задолго до людей'},story:{ja:['大気、海洋、プレート運動、生物進化、気候変動は、人類が利用できる土地・資源・生態系を長い時間をかけて形成しました。','この層は世界史とは別の「深掘り」として扱い、人間社会の説明に必要なときだけ本編へ接続します。'],ru:['Атмосфера, океаны, тектоника, эволюция и климат сформировали землю, ресурсы и экосистемы, которыми позднее пользовались люди.','Этот слой существует как углубление и подключается к основной истории тогда, когда нужен для объяснения человеческого мира.']},facts:[{ja:'範囲',ru:'Период'},'46億年前〜',{ja:'本編開始',ru:'Основная лента'},{ja:'約30万年前',ru:'≈300 тыс. лет назад'}],causes:[],outcomes:[],graph:['prehuman','sapiens','agriculture'],sameTime:[],deep:[],echoes:{structure:{ja:'地質・気候 → 生態系 → 人類の制約と機会',ru:'Геология и климат → экосистемы → ограничения и возможности людей'},same:{ja:'環境は今も社会の選択肢を制約します。',ru:'Среда и сегодня ограничивает набор социальных возможностей.'},different:{ja:'現代人は技術で環境制約を部分的に変えられます。',ru:'Современные технологии позволяют частично менять природные ограничения.'},caution:{ja:'環境だけで社会の結果を決める「環境決定論」にはしません。',ru:'CHRONOS не сводит историю к экологическому детерминизму.'}},sapiens:[],test:{question:{ja:'なぜCHRONOSの本編を地球誕生ではなくホモ・サピエンスから始めると理解しやすいと思いますか？',ru:'Почему основной CHRONOS удобнее начинать с Homo sapiens, а не с рождения Земли?'},concepts:[['人類','люд'],['社会','обществ'],['環境','сред'],['深掘','углуб']]},evidence:[]};
 const p=byPoint(id)||byPoint(currentPointId)||D.TIMEPOINTS[0];
 return {kind:{ja:'人類史の転換点',ru:'Поворот истории человечества'},title:p.title,period:l(p.label),region:{ja:p.region,ru:p.region},point:p.id,lead:{ja:`${l(p.title)}を、人類史の長い流れの中で位置づけます。`,ru:`${l(p.title)} рассматривается как часть длинной истории человечества.`},storyHeadline:{ja:'この地点を、人類史の前後関係から見る',ru:'Посмотреть на этот момент через то, что было до и после'},story:{ja:[`${l(p.label)}ごろのこの変化は、それ以前の環境・制度・技術の積み重ねの上にあります。`,'この項目は今後、地域別の史料・同時代比較・因果関係を追加して深掘りしていきます。'],ru:[`Этот сдвиг около ${l(p.label)} вырос из более ранних изменений среды, институтов и технологий.`,'Далее CHRONOS добавит источники, сравнение регионов и причинные связи для более глубокого изучения.']},facts:[{ja:'時期',ru:'Время'},p.label,{ja:'領域',ru:'Регион'},p.region],causes:[],outcomes:[],graph:[p.id],sameTime:[],deep:[],echoes:{structure:{ja:'前提条件 → 転換 → 新しい制約と機会',ru:'Условия → перелом → новые ограничения и возможности'},same:{ja:'歴史上の転換は、多くの場合一つの原因ではなく条件の組み合わせで起きます。',ru:'Исторические переломы часто возникают из сочетания условий, а не одной причины.'},different:{ja:'同じ条件があっても制度や文化が違えば結果は変わります。',ru:'Даже при похожих условиях институты и культура могут привести к иным результатам.'},caution:{ja:'類似は因果関係の証明ではありません。',ru:'Сходство само по себе не доказывает причинность.'}},sapiens:[],test:{question:{ja:`${l(p.title)}が人類史にとって重要だと思う理由を説明してください。`,ru:`Объясните, почему ${l(p.title)} важно для истории человечества.`},concepts:[['変化','измен'],['前','до'],['後','после'],['社会','обществ']]},evidence:[]};
}
const getEvent=id=>byEvent(id)||genericEvent(id);
function setTheme(v){theme=v;document.documentElement.dataset.theme=v;store.set('chronos-theme',v);$('#themeColor').content=v==='dark'?'#161715':'#eee6d5';$$('[data-theme-choice]').forEach(b=>b.classList.toggle('active',b.dataset.themeChoice===v))}
function setLang(v){lang=v;document.documentElement.lang=v;document.documentElement.dataset.lang=v;store.set('chronos-lang',v);$$('[data-i18n]').forEach(el=>{const val=t(el.dataset.i18n);if(val)el.textContent=val});$$('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));$$('.langButton,#langButton').forEach(el=>el.textContent=v==='ja'?'RU':'日本語');renderAllDynamic()}
function setDepth(v){depth=v;store.set('chronos-depth',v);$$('[data-depth]').forEach(b=>b.classList.toggle('active',b.dataset.depth===v))}
function route(){const h=(location.hash||'#home').slice(1);if(h.startsWith('event/'))return{screen:'event',id:h.split('/')[1]};return{screen:['home','timeline','library','map','profile'].includes(h)?h:'home'}}
function go(dest){const r=route();scrollMemory[r.screen]=window.scrollY;location.hash=dest}
function applyRoute(){const r=route();$$('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===r.screen));$$('.nav-action').forEach(b=>b.classList.toggle('active',b.dataset.route===r.screen));$('#topbar').hidden=r.screen==='home';if(r.screen==='event'){currentEventId=r.id;renderEvent(r.id)}if(r.screen==='timeline')requestAnimationFrame(()=>scrollTimelineToPoint(currentPointId,false));closeOverlays();requestAnimationFrame(()=>window.scrollTo(0,scrollMemory[r.screen]||0))}
function nearestPointFromSlider(value){const p=Number(value)/1000;return D.TIMEPOINTS.reduce((a,b)=>Math.abs(b.p-p)<Math.abs(a.p-p)?b:a)}
function shortLabel(p){if(p.id==='sapiens')return lang==='ja'?'30万年前':'300k';if(p.id==='agriculture')return lang==='ja'?'1万年前':'10k';return l(p.label).replace('頃','').replace('ок. ','')}
function renderDial(){const slider=$('#homeTimeSlider'),p=byPoint(currentPointId)||byPoint('atlantic1492');slider.value=Math.round(p.p*1000);$('#dialYear').textContent=l(p.label);$('#dialEvent').textContent=l(p.title);const major=D.TIMEPOINTS.filter((_,i)=>[0,2,6,8,10,14,15,18].includes(i));$('#dialTicks').innerHTML=major.map(x=>`<button class="dial-tick ${x.id===p.id?'active':''}" data-point="${x.id}" style="left:${x.p*100}%">${shortLabel(x)}</button>`).join('')}
function renderFilters(){const filters=D.FILTERS[lang];$('#timelineFilters').innerHTML=filters.map(([id,label])=>`<button class="filter-action ${timelineFilter===id?'active':''}" data-timeline-filter="${id}">${label}</button>`).join('');const lib=[['all',lang==='ja'?'すべて':'Все'],['event',lang==='ja'?'出来事':'События'],['power',lang==='ja'?'国家・帝国':'Государства'],['ideas',lang==='ja'?'宗教・思想':'Идеи'],['tech',lang==='ja'?'技術・経済':'Технологии'],['human',lang==='ja'?'環境・人類':'Среда']];$('#libraryFilters').innerHTML=lib.map(([id,label])=>`<button class="filter-action ${libraryFilter===id?'active':''}" data-library-filter="${id}">${label}</button>`).join('')}
function renderTimeline(){const canvas=$('#historyCanvas');const bands=[{p:0,n:{ja:'人類の起源',ru:'Происхождение людей'}},{p:.20,n:{ja:'農耕と定住',ru:'Земледелие и оседлость'}},{p:.38,n:{ja:'古代国家',ru:'Древние государства'}},{p:.54,n:{ja:'広域宗教と帝国',ru:'Религии и империи'}},{p:.72,n:{ja:'世界の接続',ru:'Связь миров'}},{p:.84,n:{ja:'産業化',ru:'Индустриализация'}},{p:.94,n:{ja:'世界戦争と現代',ru:'Мировые войны и современность'}}];let html=bands.map(b=>`<div class="era-band" style="left:${120+b.p*5900}px">${l(b.n)}</div>`).join('');laneY.forEach((y,i)=>{html+=`<div class="lane-line" style="top:${y}px"></div><div class="lane-label" style="top:${y}px">${laneNames[lang][i]}</div>`});html+=D.TIMEPOINTS.map(p=>{const visible=timelineFilter==='all'||p.cat===timelineFilter;return`<button class="timeline-event ${p.id===currentPointId?'focused':''}" data-point="${p.id}" style="left:${150+p.p*5900}px;top:${laneY[p.lane]}px;${visible?'':'display:none'}"><span class="t-year">${l(p.label)}</span><strong>${l(p.title)}</strong><small>${p.region}</small></button>`}).join('');canvas.innerHTML=html;const cp=byPoint(currentPointId);if(cp){$('#timelineNowYear').textContent=l(cp.label);$('#timelineNowLabel').textContent=l(cp.title)}}
function scrollTimelineToPoint(id,smooth=true){const p=byPoint(id);if(!p)return;const sc=$('#historyScroll'),left=150+p.p*5900-sc.clientWidth/2;sc.scrollTo({left:Math.max(0,left),behavior:smooth?'smooth':'auto'});currentPointId=id;store.set('chronos-point',id);renderMapForPoint(id,'timelineWorldMap');updateMapContext(id);renderDial();$$('.timeline-event').forEach(b=>b.classList.toggle('focused',b.dataset.point===id));$('#timelineNowYear').textContent=l(p.label);$('#timelineNowLabel').textContent=l(p.title)}
function handleTimelineScroll(){cancelAnimationFrame(scrollRAF);scrollRAF=requestAnimationFrame(()=>{const sc=$('#historyScroll'),x=sc.scrollLeft+sc.clientWidth/2;const p=D.TIMEPOINTS.reduce((a,b)=>Math.abs((150+b.p*5900)-x)<Math.abs((150+a.p*5900)-x)?b:a);if(p.id!==currentPointId){currentPointId=p.id;store.set('chronos-point',p.id);$('#timelineNowYear').textContent=l(p.label);$('#timelineNowLabel').textContent=l(p.title);renderMapForPoint(p.id,'timelineWorldMap');updateMapContext(p.id);renderDial();$$('.timeline-event').forEach(b=>b.classList.toggle('focused',b.dataset.point===p.id))}})}
async function loadLand(){if(worldLand)return worldLand;if(!window.d3||!window.topojson)return null;try{const world=await window.d3.json('https://cdn.jsdelivr.net/npm/world-atlas@2/land-110m.json');worldLand=topojson.feature(world,world.objects.land);return worldLand}catch{return null}}
function relatedHotspots(pointId){const p=byPoint(pointId)||byPoint('atlantic1492'),e=getEvent(eventForPoint(pointId));const spots=[{id:pointId,title:p.title,lon:p.lon,lat:p.lat,kind:'main'}];if(e.sameTime)e.sameTime.forEach((s,i)=>spots.push({id:null,title:s.title,lon:s.lon,lat:s.lat,kind:'same',note:s.text,key:`same-${i}`}));D.TIMEPOINTS.filter(x=>x.id!==p.id&&Math.abs(x.p-p.p)<.035).slice(0,3).forEach(n=>spots.push({id:n.id,title:n.title,lon:n.lon,lat:n.lat,kind:'near'}));return spots}
function drawFallbackMap(svg){const shapes=[[[80,150],[190,95],[275,120],[260,205],[185,240],[120,215]],[[315,115],[430,80],[545,105],[610,175],[560,235],[450,220],[380,260],[330,210]],[[610,125],[760,90],[890,125],[900,220],[820,255],[720,225],[660,180]],[[610,285],[700,265],[740,350],[690,440],[620,390]],[[160,290],[260,275],[300,370],[230,440],[155,395]]];shapes.forEach(s=>svg.append('path').attr('class','land').attr('d',`M${s.map(p=>p.join(',')).join('L')}Z`))}
async function renderMapForPoint(pointId,svgId){const d3x=window.d3;if(!d3x)return;const svg=d3x.select('#'+svgId);svg.selectAll('*').remove();const w=960,h=500,projection=d3x.geoNaturalEarth1().fitExtent([[18,18],[w-18,h-18]],{type:'Sphere'}),path=d3x.geoPath(projection);svg.append('path').datum(d3x.geoGraticule10()).attr('class','graticule').attr('d',path);const land=await loadLand();if(land)svg.append('path').datum(land).attr('class','land').attr('d',path);else drawFallbackMap(svg);relatedHotspots(pointId).forEach((s,i)=>{const xy=projection([s.lon,s.lat]);if(!xy)return;const color=s.kind==='main'?'var(--rust)':s.kind==='same'?'var(--gold)':'var(--olive)',g=svg.append('g').style('color',color).attr('transform',`translate(${xy[0]},${xy[1]})`).style('cursor','pointer');g.append('circle').attr('class','hotspot-ring').attr('r',14+i%2*2);g.append('circle').attr('class','hotspot').attr('r',7).attr('fill',color);g.on('click',()=>s.id?openPoint(s.id):showMapTooltip(s,svgId))})}
function showMapTooltip(s,svgId){const tip=$('#mapTooltip');if(svgId!=='timelineWorldMap'||!tip)return;tip.hidden=false;tip.innerHTML=`<strong>${l(s.title)}</strong><br><span>${l(s.note||'')}</span>`}
function updateMapContext(pointId){$('#mapContext').innerHTML=relatedHotspots(pointId).map(s=>s.id?`<button data-point="${s.id}">${l(s.title)}</button>`:`<span class="plain-context">${l(s.title)}</span>`).join('')}
function openPoint(id){currentPointId=id;store.set('chronos-point',id);go('event/'+eventForPoint(id))}
function renderEvent(id){const e=getEvent(id),point=byPoint(e.point)||byPoint(currentPointId)||D.TIMEPOINTS[0];currentPointId=point.id;$('#eventKicker').textContent=`${l(point.label)} · ${l(e.region)}`;$('#eventTitle').textContent=l(e.title);$('#eventLead').textContent=l(e.lead);$('#storyHeadline').textContent=l(e.storyHeadline);$('#storyBody').innerHTML=(l(e.story)||[]).map(p=>`<p>${p}</p>`).join('');renderFacts(e);renderEventMeta(e,point);renderConnections(e);renderSameTime(e);renderMeaning(e,'deep');renderTest(e);renderEvidence(e);renderMapForPoint(point.id,'eventWorldMap');$$('.event-tab').forEach((b,i)=>b.classList.toggle('active',i===0));$$('.event-panel').forEach((p,i)=>p.classList.toggle('active',i===0));$$('.meaning-tab').forEach(b=>b.classList.toggle('active',b.dataset.meaning==='deep'))}
function renderFacts(e){const f=e.facts||[];let html='';for(let i=0;i<f.length;i+=2)html+=`<div class="fact"><small>${l(f[i])}</small><strong>${l(f[i+1])}</strong></div>`;$('#eventFacts').innerHTML=html}
function renderEventMeta(e,p){$('#eventMeta').innerHTML=`<button data-point="${p.id}">${l(p.label)} · TIMELINE →</button><button data-event-tab-jump="world">${l(e.region)} · MAP →</button><span>${l(e.kind)}</span>`}
function renderConnections(e){$('#causeGrid').innerHTML=(e.causes||[]).map(c=>`<article class="cause-card"><div class="cause-type">${l(c.type)}</div><strong>${l(c.title)}</strong><p>${l(c.text)}</p></article>`).join('')||`<p class="page-copy">${lang==='ja'?'このテーマの複合原因データを追加中です。':'Причинные данные для этой темы ещё дополняются.'}</p>`;$('#convergence').textContent=`↓ ${l(e.title)} ↓`;$('#outcomeGrid').innerHTML=(e.outcomes||[]).map(o=>`<article class="outcome-card"><strong>${l(o.title)}</strong><p>${l(o.text)}</p></article>`).join('');renderGraph(e)}
function renderGraph(e){const ids=e.graph?.length?e.graph:[e.point],box=$('#connectionGraph');const pts=ids.map((id,i)=>{const ev=getEvent(eventForPoint(id));return{id,label:l(ev.title),x:10+(i%2)*52,y:10+Math.floor(i/2)*38}});let html='';pts.forEach((n,i)=>{html+=`<button class="graph-node action ${i===Math.floor(pts.length/2)?'center':''}" data-point="${byPoint(n.id)?n.id:(getEvent(n.id).point||n.id)}" style="left:${n.x}%;top:${n.y}%">${n.label}</button>`;if(i<pts.length-1){const b=pts[i+1],x1=n.x+9,y1=n.y+8,x2=b.x+9,y2=b.y+8,len=Math.hypot(x2-x1,y2-y1),ang=Math.atan2(y2-y1,x2-x1)*180/Math.PI;html+=`<div class="graph-line" style="left:${x1}%;top:${y1}%;width:${len}%;transform:rotate(${ang}deg)"></div>`}});box.innerHTML=html}
function renderSameTime(e){$('#sameTimeGrid').innerHTML=(e.sameTime||[]).map(s=>`<article class="same-time-card"><strong>${l(s.title)}</strong><small>${l(s.text)}</small></article>`).join('')||`<p class="page-copy">${lang==='ja'?'同時代比較を追加中です。':'Сравнение с другими регионами этой эпохи дополняется.'}</p>`}
function renderMeaning(e,mode){const out=$('#meaningContent');if(mode==='deep')out.innerHTML=`<div class="meaning-grid">${(e.deep||[]).map(x=>`<article class="meaning-card"><div class="meaning-label">${l(x.label)}</div><strong>${l(x.title)}</strong><p>${l(x.text)}</p></article>`).join('')||`<article class="meaning-card"><strong>${lang==='ja'?'別分野との接続を追加中':'Междисциплинарные связи дополняются'}</strong></article>`}</div>`;if(mode==='echoes'){const x=e.echoes||{};out.innerHTML=`<div class="echo-structure"><small class="eyebrow">STRUCTURE</small><strong>${l(x.structure||'')}</strong></div><div class="echo-columns"><article class="echo-column"><small>${lang==='ja'?'似ている構造':'Что похоже'}</small><p>${l(x.same||'')}</p></article><article class="echo-column"><small>${lang==='ja'?'現代との違い':'Что отличается'}</small><p>${l(x.different||'')}</p></article><article class="echo-column"><small>${lang==='ja'?'注意':'Ограничение'}</small><p>${l(x.caution||'')}</p></article></div>`}if(mode==='sapiens')out.innerHTML=(e.sapiens||[]).length?`<div>${e.sapiens.map(x=>`<article class="sapiens-pattern"><div class="eyebrow">HOMO SAPIENS PATTERN</div><strong>${l(x.title)}</strong><p>${l(x.text)}</p><div class="counter"><b>${lang==='ja'?'反例・条件':'Контрпример / условие'}：</b> ${l(x.counter)}</div></article>`).join('')}</div>`:`<p class="page-copy">${lang==='ja'?'この出来事から安全に言える人間行動パターンを検討中です。':'Для этой темы ещё проверяются осторожные выводы о человеческом поведении.'}</p>`}
function renderTest(e){$('#testQuestion').textContent=l(e.test?.question||{ja:'この出来事が重要な理由を説明してください。',ru:'Объясните, почему это событие важно.'});$('#testAnswer').value='';$('#testFeedback').hidden=true;$('#testFeedback').innerHTML=''}
function scoreTest(e,answer){const groups=e.test?.concepts||[],lower=answer.toLowerCase(),matched=groups.filter(g=>g.some(k=>lower.includes(k.toLowerCase()))),missing=groups.filter(g=>!g.some(k=>lower.includes(k.toLowerCase()))),ratio=groups.length?matched.length/groups.length:Math.min(1,answer.length/180),echo=l(e.echoes?.structure||'');const level=ratio>.74?(lang==='ja'?'構造としてかなり理解できています':'Вы уже хорошо видите структуру'):ratio>.4?(lang==='ja'?'重要な部分をつかめています':'Вы ухватили важную часть'):lang==='ja'?'出発点はできています':'Хорошая отправная точка';const strength=matched.length?(lang==='ja'?`特に「${matched.slice(0,2).map(g=>g[0]).join('」「')}」に触れられているので、単なる出来事の暗記ではなく原因を見ようとできています。`:`Особенно важно, что вы затронули «${matched.slice(0,2).map(g=>g[0]).join('» и «')}»: это уже причинное объяснение, а не память о фактах.`):(lang==='ja'?'まず自分の言葉で説明しようとしたことが大切です。ここから因果の部品を足していけます。':'Важно, что вы начали объяснять своими словами. Теперь можно добавить причинные элементы.');const missingText=missing.length?(lang==='ja'?`次は「${missing[0][0]}」の観点を1つ足すと、説明が一段立体的になります。`:`Добавьте ещё один ракурс — «${missing[0][0]}» — и объяснение станет заметно объёмнее.`):(lang==='ja'?'主要な観点はかなり揃っています。次は「どれが必要条件で、どれが加速要因だったか」を分けるとさらに深くなります。':'Основные элементы уже есть. Следующий шаг — отделить необходимые условия от факторов-ускорителей.');const counter=lang==='ja'?'反実仮想：もし主要な要因の1つが存在しなかったら、同じ結果になったでしょうか？ 「なくても起きた要因」と「ないと起きにくい要因」を分けてみてください。':'Контрфактический вопрос: если убрать один из ключевых факторов, произошёл бы тот же результат? Разделите ускорители и необходимые условия.';const modern=echo?(lang==='ja'?`現代への橋：${echo}。ただし「似た構造＝同じ結末」ではありません。`:`Мост к современности: ${echo}. Но похожая структура не означает одинаковый исход.`):'';const next=depth==='expert'?(lang==='ja'?'次の問い：別の地域・別の時代の類似事例と比較すると、どの要因が一般化できて、どの要因がその時代固有でしょう？':'Следующий вопрос: какие факторы можно обобщить при сравнении с другой эпохой или регионом, а какие уникальны?'):(lang==='ja'?'次の問い：「なぜこの時、この場所だったのか？」を1文で説明してみましょう。':'Следующий вопрос: объясните одним предложением «почему именно тогда и именно там?».');return{level,strength,missingText,counter,modern,next,ratio}}
function submitTest(){const e=getEvent(currentEventId),answer=$('#testAnswer').value.trim();if(answer.length<12){toast(lang==='ja'?'もう少しだけ、自分の言葉を足してみてください。':'Добавьте ещё немного своих слов.');return}const s=scoreTest(e,answer),f=$('#testFeedback');f.hidden=false;f.innerHTML=`<div class="feedback-section"><small>${lang==='ja'?'今できていること':'Что уже получается'}</small><strong>${s.level}</strong><p>${s.strength}</p></div><div class="feedback-section"><small>${lang==='ja'?'あと1つの補助線':'Один следующий штрих'}</small><p>${s.missingText}</p></div><div class="feedback-section"><small>${lang==='ja'?'一段深い考え方':'Более глубокий ход'}</small><p>${s.counter}</p></div><div class="feedback-section"><small>${lang==='ja'?'現代への橋':'Мост к современности'}</small><p>${s.modern}</p></div><div class="feedback-section"><small>${lang==='ja'?'次の問い':'Следующий вопрос'}</small><p>${s.next}</p></div>`;if(s.ratio>.4){const understood=JSON.parse(store.get('chronos-understood','[]'));if(!understood.includes(currentEventId)){understood.push(currentEventId);store.set('chronos-understood',JSON.stringify(understood));renderLearningMap()}}}
function renderEvidence(e){$('#evidenceBody').innerHTML=(e.evidence||[]).map(x=>`<div class="evidence-item"><strong>${l(x.title)}</strong><small>${l(x.level)} · ${l(x.note)}</small></div>`).join('')||`<p class="page-copy">${lang==='ja'?'このテーマの出典・論争点データを追加中です。':'Источники и дискуссионные точки для этой темы дополняются.'}</p>`}
function renderLibrary(){const all=D.LIBRARY.filter(x=>{if(libraryFilter==='all')return true;if(libraryFilter==='event')return!!D.EVENTS[x.id];const p=byPoint(x.point||x.id);return p?.cat===libraryFilter});$('#libraryGrid').innerHTML=all.map(x=>`<button class="library-card" data-library-id="${x.id}"><span class="lib-type">${l(x.type)}</span><strong>${l(x.title)}</strong><small>${x.period}</small></button>`).join('')}
function renderLearningMap(){const understood=JSON.parse(store.get('chronos-understood','[]')),pct=Math.min(100,18+understood.length*9);$('#scorePercent').textContent=pct+'%';$('.score-ring').style.background=`conic-gradient(var(--gold) 0 ${pct}%,var(--surface-2) ${pct}% 100%)`;renderMapForPoint(currentPointId,'learningWorldMap');$('#mapInsight').innerHTML=`<strong>${lang==='ja'?'あなたの理解は「ヨーロッパ近代」に偏っています':'Ваше понимание пока сильнее в новой истории Европы'}</strong><p>${lang==='ja'?'次は同じ時代の西アフリカ・東アジアを見ると、既知の出来事の見え方が変わります。':'Попробуйте Западную Африку и Восточную Азию той же эпохи — знакомые события будут выглядеть иначе.'}</p>`;$('#regionProgress').innerHTML=D.REGION_PROGRESS.map(([n,v])=>`<div class="region-row"><span>${n}</span><div class="region-track"><div class="region-fill" style="width:${v}%"></div></div><span>${v}%</span></div>`).join('')}
function renderSearch(q=''){const items=[...D.TIMEPOINTS.map(p=>({id:p.id,title:l(p.title),meta:l(p.label),point:true})),...Object.entries(D.EVENTS).map(([id,e])=>({id,title:l(e.title),meta:e.period,event:true}))],s=q.trim().toLowerCase(),filtered=items.filter(x=>!s||(x.title+' '+x.meta).toLowerCase().includes(s)).slice(0,30);$('#searchResults').innerHTML=filtered.map(x=>`<button class="search-result" ${x.event?`data-event="${x.id}"`:`data-point="${x.id}"`}><strong>${x.title}</strong><small>${x.meta}</small></button>`).join('')}
function renderAllDynamic(){renderDial();renderFilters();renderTimeline();renderLibrary();renderLearningMap();if(route().screen==='event')renderEvent(currentEventId);else{renderMapForPoint(currentPointId,'timelineWorldMap');updateMapContext(currentPointId)}}
function openSearch(){$('#searchOverlay').hidden=false;renderSearch('');setTimeout(()=>$('#searchInput').focus(),80)}
function closeOverlays(){$('#searchOverlay').hidden=true;$('#menuOverlay').hidden=true}
function toast(msg){const el=$('#toast');el.textContent=msg;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,1800)}
function toggleFullscreen(el){if(!el)return;el.classList.toggle('map-fullscreen');if(el.classList.contains('map-fullscreen'))Object.assign(el.style,{position:'fixed',inset:'0',zIndex:'120',borderRadius:'0',margin:'0',background:'var(--bg)',padding:'70px 10px 100px'});else el.removeAttribute('style')}
function clickHandler(ev){const routeBtn=ev.target.closest('[data-route]');if(routeBtn){go(routeBtn.dataset.route);return}const eventBtn=ev.target.closest('[data-event]');if(eventBtn){go('event/'+eventBtn.dataset.event);return}const pointBtn=ev.target.closest('[data-point]');if(pointBtn){currentPointId=pointBtn.dataset.point;store.set('chronos-point',currentPointId);if(route().screen==='timeline')scrollTimelineToPoint(currentPointId);else openPoint(currentPointId);return}const lib=ev.target.closest('[data-library-id]');if(lib){const id=lib.dataset.libraryId;if(D.EVENTS[id])go('event/'+id);else openPoint(D.LIBRARY.find(x=>x.id===id)?.point||id);return}const tf=ev.target.closest('[data-timeline-filter]');if(tf){timelineFilter=tf.dataset.timelineFilter;renderFilters();renderTimeline();scrollTimelineToPoint(currentPointId,false);return}const lf=ev.target.closest('[data-library-filter]');if(lf){libraryFilter=lf.dataset.libraryFilter;renderFilters();renderLibrary();return}const tab=ev.target.closest('[data-event-tab]');if(tab){$$('.event-tab').forEach(b=>b.classList.toggle('active',b===tab));$$('.event-panel').forEach(p=>p.classList.toggle('active',p.dataset.eventPanel===tab.dataset.eventTab));if(tab.dataset.eventTab==='world')renderMapForPoint(getEvent(currentEventId).point,'eventWorldMap');return}const jump=ev.target.closest('[data-event-tab-jump]');if(jump){$(`[data-event-tab="${jump.dataset.eventTabJump}"]`)?.click();return}const mt=ev.target.closest('[data-meaning]');if(mt){$$('.meaning-tab').forEach(b=>b.classList.toggle('active',b===mt));renderMeaning(getEvent(currentEventId),mt.dataset.meaning);return}const lc=ev.target.closest('[data-language-choice]');if(lc){setLang(lc.dataset.languageChoice);return}const th=ev.target.closest('[data-theme-choice]');if(th){setTheme(th.dataset.themeChoice);return}const dp=ev.target.closest('[data-depth]');if(dp){setDepth(dp.dataset.depth);return}const a=ev.target.closest('[data-action]')?.dataset.action;if(!a)return;if(a==='language')setLang(lang==='ja'?'ru':'ja');else if(a==='theme')setTheme(theme==='dark'?'light':'dark');else if(a==='search')openSearch();else if(a==='menu')$('#menuOverlay').hidden=false;else if(a==='close-menu'||a==='close-overlay')closeOverlays();else if(a==='back')history.length>1?history.back():go('timeline');else if(a==='prehuman')go('event/prehuman');else if(a==='submit-test')submitTest();else if(a==='toggle-evidence'){const b=$('#evidenceBody');b.hidden=!b.hidden;ev.target.closest('.pressable-row').querySelector(':scope > span:last-child').textContent=b.hidden?'＋':'−'}else if(a==='map-expand')toggleFullscreen($('.world-map-card'));else if(a==='graph-expand')toggleFullscreen($('.connection-map-shell'))}
document.addEventListener('click',clickHandler);window.addEventListener('hashchange',applyRoute);$('#historyScroll').addEventListener('scroll',handleTimelineScroll,{passive:true});$('#searchInput').addEventListener('input',e=>renderSearch(e.target.value));$('#homeTimeSlider').addEventListener('input',e=>{const p=nearestPointFromSlider(e.target.value);currentPointId=p.id;$('#dialYear').textContent=l(p.label);$('#dialEvent').textContent=l(p.title);$$('.dial-tick').forEach(x=>x.classList.toggle('active',x.dataset.point===p.id))});$('#homeTimeSlider').addEventListener('change',e=>{const p=nearestPointFromSlider(e.target.value);currentPointId=p.id;store.set('chronos-point',p.id);location.hash='timeline';setTimeout(()=>scrollTimelineToPoint(p.id),80)});$('#menuOverlay').addEventListener('click',e=>{if(e.target.id==='menuOverlay')closeOverlays()});$('#searchOverlay').addEventListener('click',e=>{if(e.target.id==='searchOverlay')closeOverlays()});
setTheme(theme);setLang(lang);setDepth(depth);if(!location.hash)history.replaceState(null,'','#home');applyRoute();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();
