(()=>{
'use strict';
const D=window.CHRONOS_DATA;if(!D?.TIMEPOINTS?.length)return;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const lang=()=>document.documentElement.dataset.lang||localStorage.getItem('chronos-lang')||'ja';
const l=v=>v&&typeof v==='object'&&!Array.isArray(v)?(v[lang()]??v.ja??''):String(v??'');
const ui={
 ja:{title:'人類史の巻物',before:'人類以前を見る',hint:'横へ動かして時間を旅する',wide:'広く',normal:'標準',close:'詳しく',lanes:['人類・環境','政治・帝国','思想・宗教','技術・経済'],seeWorld:'世界を見る',worldTitle:'その時代の世界',back:'年表に戻る',move:'時間を動かす',pinch:'ピンチで年表の細かさを変えられます'},
 ru:{title:'Свиток истории человечества',before:'До появления людей',hint:'Двигайте время по горизонтали',wide:'Шире',normal:'Обычно',close:'Подробнее',lanes:['Люди и среда','Политика и империи','Идеи и религии','Технологии и экономика'],seeWorld:'Открыть мир',worldTitle:'Мир этой эпохи',back:'Назад к ленте',move:'Двигайте время',pinch:'Сведите или разведите пальцы, чтобы менять детализацию'}
};
const T=()=>ui[lang()]||ui.ja;
let zoom=localStorage.getItem('chronos-timeline-zoom')||'era';
let selectedId=localStorage.getItem('chronos-point')||'atlantic1492';
let visible=[],selected=0,raf=0,land=null,pinchStart=0,pinchChanged=false,worldIndex=0;
const zoomOrder=['world','era','detail'];
const spacingFor=()=>zoom==='world'?128:zoom==='detail'?238:178;
const PAD=178;
const majorIds=new Set(D.MAJOR_DIAL_IDS||['sapiens','agriculture','writing','rome476','mongol','atlantic1492','french-revolution','ww1','postwar','today']);
function all(){return D.TIMEPOINTS.map((p,i)=>({p,i}))}
function choose(){const a=all(),n=a.length;if(zoom==='detail')return a;if(zoom==='era')return a.filter((x,j)=>majorIds.has(x.p.id)||j%2===0||j===n-1);const step=Math.max(1,Math.ceil(n/24));return a.filter((x,j)=>majorIds.has(x.p.id)||j%step===0||j===n-1)}
function eventId(p){return Object.entries(D.EVENTS||{}).find(([,e])=>e?.point===p.id)?.[0]||p.id}
function esc(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function rootMarkup(){const r=document.createElement('section');r.id='timelineV4';r.className='timeline-v4';r.innerHTML=`
 <div class="tl4-head"><div class="tl4-head-copy"><span class="tl4-eyebrow">HUMAN STORY</span><strong id="tl4Title"></strong><button class="tl4-before" data-action="prehuman"><span id="tl4Before"></span><b>↗</b></button></div><button class="tl4-world-button" id="tl4WorldButton"><span id="tl4WorldLabel"></span><b>→</b></button></div>
 <div class="tl4-focus"><div class="tl4-current"><strong id="tl4Year"></strong><span id="tl4Event"></span></div><div class="tl4-zoom" id="tl4Zoom"><button data-z="world"></button><button data-z="era"></button><button data-z="detail"></button></div></div>
 <div class="tl4-stage"><div class="tl4-ruler-title"><span id="tl4Hint"></span><small id="tl4Pinch"></small></div><div class="tl4-lane-labels" id="tl4LaneLabels"></div><div class="tl4-scroll" id="tl4Scroll"><div class="tl4-canvas" id="tl4Canvas"></div></div><div class="tl4-cursor"><i></i></div></div>`;return r}
function worldMarkup(){const s=document.createElement('section');s.id='worldTimeScreen';s.className='world-time-screen';s.hidden=true;s.innerHTML=`<div class="world-time-top"><button id="worldTimeBack" class="world-time-back">← <span></span></button><div class="wordmark">CHRONOS</div></div><main class="world-time-main"><div class="eyebrow">WORLD</div><h1 id="worldTimeTitle"></h1><div class="world-time-now"><strong id="worldTimeYear"></strong><span id="worldTimeEvent"></span></div><div class="world-time-map"><svg id="worldTimeMap" viewBox="0 0 960 520"></svg></div><div class="world-time-control"><label id="worldTimeMove"></label><input id="worldTimeSlider" type="range" min="0" max="0" step="1" value="0"><div id="worldTimeNearby"></div></div></main>`;document.body.appendChild(s)}
function mount(){if($('#timelineV4'))return;const page=$('#timelineScreen .timeline-page');if(!page)return;page.appendChild(rootMarkup());worldMarkup();bind();renderLanguage();setZoom(zoom,false)}
function renderLanguage(){const t=T();$('#tl4Title').textContent=t.title;$('#tl4Before').textContent=t.before;$('#tl4Hint').textContent=t.hint;$('#tl4Pinch').textContent=t.pinch;$('#tl4WorldLabel').textContent=t.seeWorld;const z=$$('#tl4Zoom button');if(z.length){z[0].textContent=t.wide;z[1].textContent=t.normal;z[2].textContent=t.close}$('#tl4LaneLabels').innerHTML=t.lanes.map((x,i)=>`<span style="--lane:${i}">${x}</span>`).join('');$('#worldTimeBack span').textContent=t.back;$('#worldTimeTitle').textContent=t.worldTitle;$('#worldTimeMove').textContent=t.move;renderWindow(true);if(!$('#worldTimeScreen').hidden)renderWorld(worldIndex)}
function nearestVisibleId(id){let k=visible.findIndex(x=>x.p.id===id);if(k>=0)return k;const full=D.TIMEPOINTS.findIndex(p=>p.id===id);if(full<0)return 0;let best=0,dist=1e9;visible.forEach((x,i)=>{const d=Math.abs(x.i-full);if(d<dist){dist=d;best=i}});return best}
function setZoom(z,keep=true){const old=visible[selected]?.p?.id||selectedId;zoom=z;localStorage.setItem('chronos-timeline-zoom',z);visible=choose();selected=nearestVisibleId(keep?old:selectedId);$$('#tl4Zoom button').forEach(b=>b.classList.toggle('active',b.dataset.z===zoom));const c=$('#tl4Canvas');if(c)c.style.width=(PAD*2+Math.max(0,visible.length-1)*spacingFor())+'px';requestAnimationFrame(()=>centerOn(selected,false))}
function centerOn(i,smooth=true){selected=Math.max(0,Math.min(visible.length-1,i));const sc=$('#tl4Scroll');if(!sc)return;const x=PAD+selected*spacingFor();sc.scrollTo({left:Math.max(0,x-sc.clientWidth/2),behavior:smooth?'smooth':'auto'});updateSelected(true);renderWindow()}
function syncLegacy(fullIndex){const old=$('#historyScroll');if(!old)return;try{old.scrollLeft=Math.max(0,128+fullIndex*246-195);old.dispatchEvent(new Event('scroll'))}catch{}}
function updateSelected(sync=false){const x=visible[selected];if(!x)return;selectedId=x.p.id;localStorage.setItem('chronos-point',selectedId);$('#tl4Year').textContent=l(x.p.label);$('#tl4Event').textContent=l(x.p.title);if(sync)syncLegacy(x.i)}
function renderWindow(force=false){const sc=$('#tl4Scroll'),canvas=$('#tl4Canvas');if(!sc||!canvas||!visible.length)return;const spacing=spacingFor(),center=Math.round((sc.scrollLeft+sc.clientWidth/2-PAD)/spacing),radius=Math.ceil(sc.clientWidth/spacing)+12,lo=Math.max(0,center-radius),hi=Math.min(visible.length-1,center+radius),key=`${zoom}:${lo}:${hi}:${lang()}:${selected}`;if(!force&&canvas.dataset.key===key)return;canvas.dataset.key=key;let h='';for(let i=0;i<4;i++)h+=`<div class="tl4-lane-line" style="--lane:${i}"></div>`;const rulerEvery=zoom==='detail'?3:zoom==='era'?2:1;for(let j=lo;j<=hi;j++){const {p}=visible[j],x=PAD+j*spacing,focus=j===selected;if(j%rulerEvery===0||focus)h+=`<span class="tl4-tick ${focus?'focused':''}" style="left:${x}px"><b></b><em>${esc(l(p.label))}</em></span>`;h+=`<button class="tl4-event ${focus?'focused':''}" data-event="${esc(eventId(p))}" style="left:${x}px;--lane:${p.lane??0}"><small>${esc(l(p.label))}</small><strong>${esc(l(p.title))}</strong><span>${esc(p.region||'')}</span></button>`}canvas.innerHTML=h}
function onScroll(){cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{const sc=$('#tl4Scroll');if(!sc)return;const i=Math.max(0,Math.min(visible.length-1,Math.round((sc.scrollLeft+sc.clientWidth/2-PAD)/spacingFor())));if(i!==selected){selected=i;updateSelected(true)}renderWindow()})}
function pinchDistance(t){if(t.length<2)return 0;const dx=t[0].clientX-t[1].clientX,dy=t[0].clientY-t[1].clientY;return Math.hypot(dx,dy)}
function onTouchStart(e){if(e.touches.length===2){pinchStart=pinchDistance(e.touches);pinchChanged=false}}
function onTouchMove(e){if(e.touches.length!==2||!pinchStart||pinchChanged)return;const d=pinchDistance(e.touches),ratio=d/pinchStart;if(ratio>1.18||ratio<.82){e.preventDefault();const idx=zoomOrder.indexOf(zoom),next=ratio>1.18?Math.min(2,idx+1):Math.max(0,idx-1);if(next!==idx)setZoom(zoomOrder[next]);pinchChanged=true}}
function onTouchEnd(e){if(e.touches.length<2){pinchStart=0;pinchChanged=false}}
async function getLand(){if(land)return land;if(!window.d3||!window.topojson)return null;try{const w=await d3.json('https://cdn.jsdelivr.net/npm/world-atlas@2/land-110m.json');return land=topojson.feature(w,w.objects.land)}catch{return null}}
function nearbyFull(i,r=5){return all().slice(Math.max(0,i-r),Math.min(D.TIMEPOINTS.length,i+r+1))}
async function drawWorld(svg,p,i){if(!svg||!p)return;const ld=await getLand();if(ld&&window.d3){const pr=d3.geoNaturalEarth1().fitSize([930,500],ld),path=d3.geoPath(pr);let h=`<path class="wt-graticule" d="${path(d3.geoGraticule10())}"></path><path class="wt-land" d="${path(ld)}"></path>`;nearbyFull(i,6).forEach(({p:q})=>{const xy=pr([q.lon||0,q.lat||0]);if(!xy)return;const on=q.id===p.id;h+=`<g><circle class="wt-ring ${on?'active':''}" cx="${xy[0]}" cy="${xy[1]}" r="${on?16:11}"></circle><circle class="wt-dot ${on?'active':''}" cx="${xy[0]}" cy="${xy[1]}" r="${on?6:4.5}"></circle></g>`});svg.innerHTML=h}else svg.innerHTML='<rect width="960" height="520" fill="transparent"/><g fill="rgba(220,210,190,.15)"><ellipse cx="210" cy="190" rx="120" ry="75"/><ellipse cx="300" cy="330" rx="62" ry="112"/><ellipse cx="555" cy="195" rx="170" ry="90"/><ellipse cx="610" cy="335" rx="72" ry="105"/><ellipse cx="820" cy="380" rx="72" ry="48"/></g>'}
async function renderWorld(i){worldIndex=Math.max(0,Math.min(D.TIMEPOINTS.length-1,i));const p=D.TIMEPOINTS[worldIndex];$('#worldTimeYear').textContent=l(p.label);$('#worldTimeEvent').textContent=l(p.title);const sl=$('#worldTimeSlider');sl.max=D.TIMEPOINTS.length-1;sl.value=worldIndex;await drawWorld($('#worldTimeMap'),p,worldIndex);$('#worldTimeNearby').innerHTML=nearbyFull(worldIndex,4).map(({p:q})=>`<button data-world-point="${esc(q.id)}" class="${q.id===p.id?'active':''}"><small>${esc(l(q.label))}</small><span>${esc(l(q.title))}</span></button>`).join('')}
function openWorld(){const full=visible[selected]?.i??D.TIMEPOINTS.findIndex(p=>p.id===selectedId);worldIndex=Math.max(0,full);$('#worldTimeScreen').hidden=false;document.documentElement.classList.add('world-time-open');renderWorld(worldIndex)}
function closeWorld(){$('#worldTimeScreen').hidden=true;document.documentElement.classList.remove('world-time-open');const p=D.TIMEPOINTS[worldIndex];if(p){selectedId=p.id;localStorage.setItem('chronos-point',p.id);visible=choose();selected=nearestVisibleId(p.id);setTimeout(()=>centerOn(selected,false),20)}}
function bind(){const sc=$('#tl4Scroll');sc.addEventListener('scroll',onScroll,{passive:true});sc.addEventListener('touchstart',onTouchStart,{passive:true});sc.addEventListener('touchmove',onTouchMove,{passive:false});sc.addEventListener('touchend',onTouchEnd,{passive:true});$('#tl4Zoom').addEventListener('click',e=>{const b=e.target.closest('[data-z]');if(b)setZoom(b.dataset.z)});$('#tl4WorldButton').addEventListener('click',openWorld);$('#worldTimeBack').addEventListener('click',closeWorld);$('#worldTimeSlider').addEventListener('input',e=>renderWorld(+e.target.value));$('#worldTimeNearby').addEventListener('click',e=>{const b=e.target.closest('[data-world-point]');if(!b)return;const i=D.TIMEPOINTS.findIndex(p=>p.id===b.dataset.worldPoint);if(i>=0)renderWorld(i)});window.addEventListener('resize',()=>{if($('#worldTimeScreen')?.hidden!==false)centerOn(selected,false)},{passive:true});const mo=new MutationObserver(m=>{if(m.some(x=>x.attributeName==='data-lang'||x.attributeName==='lang'))renderLanguage()});mo.observe(document.documentElement,{attributes:true,attributeFilter:['data-lang','lang']})}
function routeWatch(){if((location.hash||'#home').slice(1)==='timeline'){selectedId=localStorage.getItem('chronos-point')||selectedId;visible=choose();selected=nearestVisibleId(selectedId);setTimeout(()=>centerOn(selected,false),40)}else if($('#worldTimeScreen')&&!$('#worldTimeScreen').hidden)closeWorld()}
mount();routeWatch();window.addEventListener('hashchange',routeWatch);
})();