(()=>{
'use strict';
const $=s=>document.querySelector(s);
let currentLang='ja';
let currentTopic=null;
const text={
 ja:{title:'テーマから旅する',copy:'年代を覚える前に、気になる世界へ。ひとつのテーマから、暮らし・宗教・戦争・技術・他地域への影響までつながりでたどります。',recommended:'最初のおすすめ',more:'もっと旅する',back:'テーマ一覧へ',timeline:'この時代を年表で見る',related:'関連する旅',close:'CHRONOSへ戻る'},
 ru:{title:'Путешествовать по темам',copy:'Начните не с запоминания дат, а с мира, который вас заинтересовал. Одна тема связывает быт, религию, войны, технологии и влияние на другие регионы.',recommended:'Рекомендуем начать',more:'Другие путешествия',back:'Все темы',timeline:'Посмотреть эту эпоху на ленте',related:'Связанные путешествия',close:'Вернуться в CHRONOS'}
};
const topics={
 viking:{media:'Viking ship Oseberg museum',point:'viking',period:{ja:'793–1066',ru:'793–1066'},title:{ja:'ヴァイキング時代',ru:'Эпоха викингов'},sub:{ja:'海を越えた人々',ru:'Люди, пересекавшие моря'},hook:{ja:'なぜ北欧の人々は、世界へ出ていったのか？',ru:'Почему жители Севера вышли в море и изменили Европу?'},intro:{ja:'ヴァイキングを「略奪者」だけで見ると、この時代の半分しか見えません。船の技術、農村の暮らし、交易、名誉と権力、北欧神話、移住、そしてイングランドなど各地の国家形成までを一つにつなげて見ます。',ru:'Если видеть викингов только как грабителей, мы теряем половину картины. Корабли, сельский быт, торговля, честь и власть, скандинавская мифология, переселения и формирование государств образуют одну историю.'},chapters:[
  {title:{ja:'北欧神話と世界観',ru:'Скандинавская мифология и картина мира'},body:{ja:'オーディン、トール、ラグナロクなどの物語は、単なる神話ではありません。共同体が勇気、名誉、死、運命をどう捉えたのかを知る手がかりです。キリスト教化が進むと、古い信仰は消えるだけでなく、新しい宗教と混ざりながら社会の価値観を変えていきました。',ru:'Истории об Одине, Торе и Рагнарёке показывают, как общество понимало честь, смерть и судьбу. С распространением христианства старые верования не просто исчезали, а сосуществовали и смешивались с новой религией.'}},
  {title:{ja:'衣服・食事・暮らし',ru:'Одежда, еда и повседневность'},body:{ja:'多くの人々は農耕、牧畜、漁業、手工業で暮らしていました。遠征は社会全体の日常ではなく、季節、家族、土地、交易と結びついた活動でした。衣服や装飾品からは、地域間の交易や身分の差も見えてきます。',ru:'Большинство людей жили земледелием, скотоводством, рыболовством и ремёслами. Походы были связаны с сезоном, семьёй, землёй и торговлей. Одежда и украшения показывают и торговые связи, и различия в статусе.'}},
  {title:{ja:'なぜ海へ出たのか',ru:'Почему они вышли в море'},body:{ja:'理由は一つではありません。浅い海や川を進める船、富と地位を求める競争、人口移動、交易の利益、そして周辺地域の政治的な分裂が重なりました。技術があったから征服したのではなく、技術を使う社会的な動機が同時に存在したのです。',ru:'Причина была не одна: корабельные технологии, борьба за богатство и статус, миграции, выгоды торговли и политическая раздробленность соседей действовали одновременно.'}},
  {title:{ja:'征服だけではない交易網',ru:'Не только завоевания: торговые сети'},body:{ja:'ヴァイキングの活動範囲は北大西洋だけではありません。バルト海、ルーシ、ビザンツ、イスラーム世界まで銀、毛皮、奴隷、工芸品などが動きました。戦争と交易は別々ではなく、同じ移動ネットワークの中で起きていました。',ru:'Сети викингов связывали не только Северную Атлантику, но и Балтику, Русь, Византию и исламский мир. Война и торговля существовали внутри одной системы мобильности.'}},
  {title:{ja:'イングランドと国家形成',ru:'Англия и формирование государств'},body:{ja:'襲撃から定住へ、デーンロウから王国統合へ。ヴァイキングとの競争は、イングランド側の徴税、軍事、統治の仕組みも変えました。外からの圧力が、国家のまとまりを強める場合があることが分かります。',ru:'Переход от набегов к поселениям и борьба за Данелаг меняли и английские институты: налоги, военную организацию и управление. Внешнее давление иногда ускоряет централизацию государства.'}}
 ],related:['crusades','silk','mongol']},
 egypt:{media:'Great Pyramids Giza Egypt',point:'pyramids',period:{ja:'古代',ru:'Древность'},title:{ja:'古代エジプト',ru:'Древний Египет'},sub:{ja:'死後の世界とピラミッド',ru:'Загробный мир и пирамиды'},hook:{ja:'なぜ人々は、巨大な墓を造ったのか？',ru:'Почему люди строили такие огромные гробницы?'},intro:{ja:'ピラミッドを建築技術だけで見るのではなく、ナイル川、王権、宗教、徴税、労働組織、文字という国家の仕組みから読み解きます。',ru:'Пирамиды становятся понятнее, если смотреть на Нил, царскую власть, религию, налоги, организацию труда и письмо как на единую систему.'},chapters:[
 {title:{ja:'ナイル川がつくった生活',ru:'Жизнь, созданная Нилом'},body:{ja:'毎年の氾濫は農耕を支えましたが、水と土地を管理するには測量、協力、記録が必要でした。自然環境がそのまま国家を生んだのではなく、環境への対応が組織を発達させました。',ru:'Ежегодние разливы поддерживали земледелие, но управление водой и землёй требовало измерений, сотрудничества и учёта.'}},
 {title:{ja:'王権と宗教',ru:'Царская власть и религия'},body:{ja:'王は政治的な支配者であるだけでなく、世界の秩序を維持する存在と考えられました。巨大建築は権力の誇示であると同時に、宗教的な秩序を形にする行為でもありました。',ru:'Царь считался не только политическим правителем, но и хранителем порядка мира. Монументальная архитектура была и демонстрацией власти, и религиозным действием.'}},
 {title:{ja:'死後の世界',ru:'Загробный мир'},body:{ja:'死後も人格や社会的秩序が続くという考えが、ミイラ、墓、葬祭文書、供物、職人文化を発達させました。',ru:'Представление о продолжении жизни после смерти способствовало развитию мумификации, гробниц, погребальных текстов и ремёсел.'}},
 {title:{ja:'ピラミッドを可能にした国家',ru:'Государство, сделавшее пирамиды возможными'},body:{ja:'石を積む技術だけでは足りません。大量の食料、労働者の編成、輸送、測量、行政、記録を長期間維持できる国家能力が必要でした。',ru:'Одной строительной технологии было недостаточно: требовались снабжение, транспорт, измерения, учёт и способность государства долго координировать труд.'}}
 ],related:['silk','exploration','french']},
 french:{media:'French Revolution Bastille 1789 painting',point:'french-revolution',period:{ja:'1789–1799',ru:'1789–1799'},title:{ja:'フランス革命',ru:'Французская революция'},sub:{ja:'世界がひっくり返った日々',ru:'Годы, изменившие политический мир'},hook:{ja:'なぜ普通の人々が、王のいる世界を壊したのか？',ru:'Почему кризис монархии превратился в революцию?'},intro:{ja:'「貧しかったから革命が起きた」では足りません。戦争による借金、税の不公平、食料価格、政治参加への要求、啓蒙思想、大西洋世界の変化が同じ時期に重なったことが重要です。',ru:'Формулы «революция произошла из-за бедности» недостаточно. Долги войны, неравные налоги, цены на хлеб, требования представительства, Просвещение и изменения Атлантического мира совпали во времени.'},chapters:[
 {title:{ja:'戦争に勝つほどお金が必要だった',ru:'Чем больше войн, тем больше денег требовалось'},body:{ja:'七年戦争とアメリカ独立戦争への介入は、フランスの国家財政を圧迫しました。問題は単なる王家の浪費ではなく、近世国家の軍事費と税制の構造にありました。',ru:'Семилетняя война и участие в войне за независимость США усилили финансовое давление. Проблема была не только в расходах двора, но и в устройстве военных финансов и налогов.'}},
 {title:{ja:'税の問題が政治制度の問題へ',ru:'Налоговый кризис становится политическим'},body:{ja:'財政再建には新しい負担が必要でしたが、特権身分への課税は「誰が税を決めるのか」「誰が国を代表するのか」という正統性の問題を引き起こしました。',ru:'Попытки расширить налогообложение привели к вопросу: кто имеет право решать, кто платит и кто представляет страну?'}},
 {title:{ja:'パンと生活危機',ru:'Хлеб и кризис повседневности'},body:{ja:'穀物価格の上昇は抽象的な政治危機を日常生活の危機へ変えました。政治への不満と生活不安が同時に高まると、制度への信頼は急速に崩れやすくなります。',ru:'Рост цен на зерно превратил политический кризис в кризис повседневности и ускорил падение доверия к институтам.'}},
 {title:{ja:'1789年の連鎖',ru:'Цепь событий 1789 года'},body:{ja:'三部会、国民議会、バスティーユ襲撃、人権宣言が短い期間に続き、「王が統治する国」から「誰が主権を持つのか」を争う政治へ変わりました。',ru:'Генеральные штаты, Национальное собрание, Бастилия и Декларация прав быстро изменили сам вопрос о том, кому принадлежит суверенитет.'}}
 ],related:['exploration','crusades','viking']},
 silk:{media:'Silk Road caravan mural',point:'silk-road',period:{ja:'古代〜中世',ru:'Древность–Средневековье'},title:{ja:'シルクロード',ru:'Шёлковый путь'},sub:{ja:'世界をつないだ交易網',ru:'Сети, связывавшие Евразию'},hook:{ja:'モノだけでなく、宗教や病気までどう移動したのか？',ru:'Как вместе с товарами перемещались идеи, религии и болезни?'},intro:{ja:'一本の道ではなく、都市・砂漠・草原・海路が重なる巨大なネットワークとして見ます。',ru:'Это была не одна дорога, а огромная сеть городов, степей, пустынь и морских маршрутов.'},chapters:[],related:['mongol','viking','crusades']},
 mongol:{media:'Mongol Empire manuscript horsemen',point:'mongol',period:{ja:'13世紀',ru:'XIII век'},title:{ja:'モンゴル帝国',ru:'Монгольская империя'},sub:{ja:'草原から広がった巨大帝国',ru:'Империя, выросшая из степи'},hook:{ja:'なぜ短期間でユーラシアの広大な地域を結べたのか？',ru:'Почему огромная часть Евразии оказалась связана так быстро?'},intro:{ja:'軍事力だけでなく、草原社会、騎馬技術、情報伝達、交易、宗教政策までをつなげて見ます。',ru:'Смотрим не только на войну, но и на степное общество, мобильность, связь, торговлю и религиозную политику.'},chapters:[],related:['silk','viking','crusades']},
 crusades:{media:'Crusades medieval manuscript',point:'crusades',period:{ja:'11〜13世紀',ru:'XI–XIII века'},title:{ja:'十字軍',ru:'Крестовые походы'},sub:{ja:'信仰・政治・交易が交差した時代',ru:'Вера, политика и торговля'},hook:{ja:'宗教だけで説明すると、何を見落とすのか？',ru:'Что теряется, если объяснять крестовые походы только религией?'},intro:{ja:'信仰、教皇権、騎士社会、土地、都市、交易という複数の動機が重なった出来事として見ます。',ru:'Религиозная вера, папская власть, рыцарское общество, земля, города и торговля действовали одновременно.'},chapters:[],related:['viking','silk','mongol']},
 exploration:{media:'Age of Discovery historical ships map',point:'atlantic1492',period:{ja:'15〜17世紀',ru:'XV–XVII века'},title:{ja:'大航海時代',ru:'Эпоха океанских экспедиций'},sub:{ja:'海でつながった世界',ru:'Мир, связанный океанами'},hook:{ja:'なぜ海路の拡大が世界の経済と人口まで変えたのか？',ru:'Почему новые морские пути изменили экономику и население мира?'},intro:{ja:'航海技術、国家競争、銀、植民地化、疫病、作物交換を一つの世界的なつながりとして見ます。',ru:'Навигация, конкуренция государств, серебро, колонизация, болезни и обмен культурами образуют единую мировую систему.'},chapters:[],related:['french','silk','egypt']}
};
const order=['viking','egypt','french','silk','mongol','crusades','exploration'];
function l(v){return v?.[currentLang]??v?.ja??''}
function escapeHtml(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function card(id,featured=false){const t=topics[id];return `<button class="topic-card${featured?' featured':''}" data-topic="${id}" type="button"><span class="topic-card-media" data-media="${id}"><img alt="${escapeHtml(l(t.title))}"></span><span class="topic-card-shade"></span><span class="topic-card-arrow">→</span><span class="topic-card-copy"><small>${escapeHtml(l(t.period))}</small><strong>${escapeHtml(l(t.title))}</strong><em>${escapeHtml(l(t.sub))}</em><p>${escapeHtml(l(t.hook))}</p></span></button>`}
function renderList(){currentTopic=null;document.documentElement.dataset.lang=currentLang;document.documentElement.lang=currentLang;$('#topicsLang').textContent=currentLang==='ja'?'RU':'JA';$('#topicsTitle').textContent=text[currentLang].title;$('#topicsCopy').textContent=text[currentLang].copy;$('#recommendLabel').textContent=text[currentLang].recommended;$('#topicsGrid').innerHTML=card('viking',true)+card('egypt')+card('french')+`<div class="topics-preview-section-label">${text[currentLang].more}</div>`+order.slice(3).map(id=>card(id)).join('');$('#topicsList').hidden=false;$('#topicDetail').hidden=true;bindCards($('#topicsGrid'));hydrateImages($('#topicsGrid'));window.scrollTo({top:0,behavior:'instant'})}
function renderDetail(id){currentTopic=id;const t=topics[id];const related=(t.related||[]).map(r=>`<button type="button" data-topic="${r}"><small>${escapeHtml(l(topics[r].period))}</small><strong>${escapeHtml(l(topics[r].title))}</strong></button>`).join('');const chapters=t.chapters.length?t.chapters.map((c,i)=>`<article class="topic-chapter"><button type="button" data-chapter="${i}"><small>${String(i+1).padStart(2,'0')}</small><strong>${escapeHtml(l(c.title))}</strong><b>＋</b></button><div class="topic-chapter-body" hidden><p>${escapeHtml(l(c.body))}</p></div></article>`).join(''):`<article class="topic-chapter"><button type="button"><small>01</small><strong>${currentLang==='ja'?'このテーマの章は次の実装で追加':'Разделы будут добавлены на следующем этапе'}</strong><b></b></button></article>`;$('#topicDetail').innerHTML=`<button class="topics-preview-back" id="topicBack" type="button">← ${text[currentLang].back}</button><div class="topic-detail-hero"><span class="topic-card-media" data-media="${id}"><img alt="${escapeHtml(l(t.title))}"></span><span class="topic-card-shade"></span><div class="topic-detail-hero-copy"><small>${escapeHtml(l(t.period))}</small><h1>${escapeHtml(l(t.title))}</h1><strong>${escapeHtml(l(t.sub))}</strong><p>${escapeHtml(l(t.hook))}</p></div></div><p class="topic-detail-intro">${escapeHtml(l(t.intro))}</p><div class="topic-detail-actions"><button class="primary" type="button" id="topicTimeline">${text[currentLang].timeline}</button></div><div class="topic-chapters">${chapters}</div><section class="topic-related"><h2>${text[currentLang].related}</h2><div class="topic-related-row">${related}</div></section>`;$('#topicsList').hidden=true;$('#topicDetail').hidden=false;$('#topicBack').onclick=renderList;$('#topicTimeline').onclick=()=>openTimeline(t.point);$('#topicDetail').querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>{const body=b.nextElementSibling;if(!body)return;body.hidden=!body.hidden;b.querySelector('b').textContent=body.hidden?'＋':'−'});bindCards($('#topicDetail'));hydrateImages($('#topicDetail'));window.scrollTo({top:0,behavior:'instant'})}
function bindCards(root){root.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>renderDetail(b.dataset.topic))}
function openTimeline(point){try{localStorage.setItem('chronos-point',point)}catch{}location.href='./#timeline'}
async function commonsImage(query){const api='https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrnamespace=6&gsrlimit=10&gsrsearch='+encodeURIComponent(query)+'&prop=imageinfo&iiprop=url&iiurlwidth=1000&format=json&origin=*';try{const r=await fetch(api);if(!r.ok)return null;const j=await r.json();const pages=Object.values(j?.query?.pages||{}).filter(p=>/\.(jpe?g|png|webp)$/i.test(p.title||'')&&!/(chart|graph|plot|diagram|logo|icon|flag)/i.test(p.title||''));const hit=pages.find(p=>p.imageinfo?.[0]?.thumburl);return hit?.imageinfo?.[0]?.thumburl||null}catch{return null}}
function hydrateImages(root){root.querySelectorAll('[data-media]').forEach(async box=>{const id=box.dataset.media;if(box.dataset.loading)return;box.dataset.loading='1';const img=box.querySelector('img');const url=await commonsImage(topics[id].media);if(url){img.onload=()=>img.classList.add('ready');img.src=url}else box.classList.add('fallback')})}
$('#topicsLang').onclick=()=>{currentLang=currentLang==='ja'?'ru':'ja';currentTopic?renderDetail(currentTopic):renderList()};
renderList();
})();
