(()=>{
'use strict';
const D=window.CHRONOS_DATA||{};
const M=window.CHRONOS_MEDIA;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const lang=()=>document.documentElement.dataset.lang||localStorage.getItem('chronos-lang')||'ja';
const ja=()=>lang()==='ja';
const l=v=>v&&typeof v==='object'&&!Array.isArray(v)?(v[lang()]??v.ja??''):String(v??'');
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const read=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
const topicData={
 viking:{query:'Oseberg Viking ship museum',period:{ja:'793–1066',ru:'793–1066'},title:{ja:'ヴァイキング時代',ru:'Эпоха викингов'},sub:{ja:'海を越えた人々',ru:'Люди, пересекавшие моря'},hook:{ja:'なぜ北欧の人々は、世界へ出ていったのか？',ru:'Почему жители Севера вышли в море и изменили Европу?'},intro:{ja:'略奪だけではなく、船・交易・信仰・移住・政治競争を一緒に見ると、ヴァイキング時代が北欧とヨーロッパの国家形成までつながって見えてきます。',ru:'Если смотреть не только на набеги, но и на корабли, торговлю, веру, переселение и политическую конкуренцию, эпоха викингов становится частью истории формирования государств.'},chapters:[['北欧神話と世界観','Скандинавская мифология','神々の物語は、共同体の価値観や死の捉え方、権力と結びついていました。','Мифы были связаны с ценностями общины, властью и представлениями о смерти.'],['衣服・食事・暮らし','Одежда, еда и быт','農耕、牧畜、漁業、手工業が生活の基盤でした。遠征は社会の一部で、日常のすべてではありません。','Основой жизни были земледелие, скотоводство, рыболовство и ремёсла. Походы были лишь частью общества.'],['なぜ海へ出たのか','Почему они вышли в море','高性能な船、富と地位をめぐる競争、交易機会、近隣地域の政治状況が重なりました。','Корабельные технологии, борьба за статус, торговые возможности и политическая ситуация соседей действовали вместе.'],['征服と交易','Завоевание и торговля','略奪・交易・傭兵・移住は連続しており、バルト海からビザンツ、イスラーム世界までつながりました。','Набеги, торговля, наёмничество и переселение связывали Балтику с Византией и исламским миром.'],['イングランドと国家形成','Англия и формирование государств','定住、デーンロウ、王国間競争、ノルマン征服への流れから国家形成との関係を見ます。','Поселения, Данелаг и борьба королевств связывают эпоху викингов с формированием государств.']]},
 egypt:{query:'Great Pyramids Giza Egypt',period:{ja:'古代',ru:'Древность'},title:{ja:'古代エジプト',ru:'Древний Египет'},sub:{ja:'死後の世界とピラミッド',ru:'Загробный мир и пирамиды'},hook:{ja:'なぜ人々は、巨大な墓を造ったのか？',ru:'Почему люди строили такие огромные гробницы?'},intro:{ja:'ナイル川、王権、宗教、労働組織、文字を一緒に見ると、ピラミッドは「建築の謎」ではなく国家のしくみとして見えてきます。',ru:'Нил, царская власть, религия, организация труда и письмо показывают пирамиды не как загадку, а как результат устройства государства.'},chapters:[['ナイル川がつくった生活','Жизнь, созданная Нилом','氾濫は農耕を支え、水と土地の管理は協力と組織を必要としました。','Разливы поддерживали земледелие, а управление водой и землёй требовало организации.'],['王権と宗教','Царская власть и религия','王は行政だけでなく、秩序や宗教の中心として理解されました。','Царь был не только правителем, но и центром религиозного и космического порядка.'],['死後の世界','Загробный мир','死後も秩序が続くという信仰が、墓、ミイラ、葬祭文書、職人文化を生みました。','Вера в продолжение порядка после смерти породила гробницы, мумификацию, тексты и ремёсла.'],['ピラミッドを可能にしたもの','Что сделало пирамиды возможными','技術だけでなく、食料供給、徴税、測量、労働編成という国家能力が必要でした。','Нужны были не только технологии, но и снабжение, налоги, измерения и организация труда.']]},
 french:{query:'French Revolution Bastille 1789 painting',period:{ja:'1789–1799',ru:'1789–1799'},title:{ja:'フランス革命',ru:'Французская революция'},sub:{ja:'世界がひっくり返った日々',ru:'Годы, изменившие политический мир'},hook:{ja:'なぜ普通の人々が、王のいる世界を壊したのか？',ru:'Почему кризис монархии превратился в революцию?'},intro:{ja:'戦争による借金、税の不公平、食料危機、啓蒙思想、代表制の問題が、どう一つの政治危機へ収束したのかを見ます。',ru:'Долги войны, налоги, продовольственный кризис, идеи Просвещения и вопрос представительства сошлись в одном политическом кризисе.'},chapters:[['戦争と国家財政','Войны и государственные финансы','七年戦争とアメリカ独立戦争への介入で国家債務が膨らみました。','Семилетняя война и участие в войне за независимость США увеличили государственный долг.'],['税と特権','Налоги и привилегии','財政改革は「誰が負担するのか」という身分制度の問題にぶつかりました。','Финансовая реформа упёрлась в вопрос о том, кто должен платить.'],['パンと生活危機','Хлеб и кризис повседневности','価格上昇は政治論争を生活の切迫した問題へ変えました。','Рост цен сделал политический кризис частью повседневной жизни.'],['1789年の連鎖','Цепь событий 1789 года','三部会、国民議会、バスティーユ、人権宣言が短期間に続き、代表のルールが変化しました。','Генеральные штаты, Национальное собрание, Бастилия и Декларация прав быстро изменили правила представительства.']]},
 silk:{query:'Silk Road caravan mural',period:{ja:'古代〜中世',ru:'Древность–Средневековье'},title:{ja:'シルクロード',ru:'Шёлковый путь'},sub:{ja:'世界をつないだ交易網',ru:'Сети, связывавшие Евразию'},hook:{ja:'モノだけでなく、宗教や病気までどう移動したのか？',ru:'Как вместе с товарами перемещались идеи, религии и болезни?'},intro:{ja:'一本の道ではなく、都市・砂漠・草原・海路が重なったネットワークとして見ます。',ru:'Это была не одна дорога, а сеть городов, степей, пустынь и морских маршрутов.'},chapters:[]},
 mongol:{query:'Mongol Empire manuscript horsemen',period:{ja:'13世紀',ru:'XIII век'},title:{ja:'モンゴル帝国',ru:'Монгольская империя'},sub:{ja:'草原から広がった巨大帝国',ru:'Империя, выросшая из степи'},hook:{ja:'なぜ短期間でユーラシアの広大な地域を結べたのか？',ru:'Почему огромная часть Евразии оказалась связана так быстро?'},intro:{ja:'軍事力だけでなく、草原社会、情報伝達、交易、宗教政策まで一緒に見ます。',ru:'Рассматриваем не только военную силу, но и степное общество, связь, торговлю и религиозную политику.'},chapters:[]},
 crusades:{query:'Crusades medieval manuscript',period:{ja:'11–13世紀',ru:'XI–XIII века'},title:{ja:'十字軍',ru:'Крестовые походы'},sub:{ja:'信仰・政治・交易が交差した時代',ru:'Вера, политика и торговля'},hook:{ja:'宗教だけで説明すると、何を見落とすのか？',ru:'Что теряется, если объяснять крестовые походы только религией?'},intro:{ja:'信仰、権力、土地、交易、都市の成長が重なる出来事として見ます。',ru:'Рассматриваем веру, власть, землю, торговлю и рост городов как взаимосвязанные силы.'},chapters:[]},
 exploration:{query:'Age of Discovery historical map ships',period:{ja:'15–17世紀',ru:'XV–XVII века'},title:{ja:'大航海時代',ru:'Эпоха Великих географических открытий'},sub:{ja:'海でつながった世界',ru:'Мир, связанный океанами'},hook:{ja:'なぜ海路の拡大が世界の経済と人口まで変えたのか？',ru:'Почему морские пути изменили экономику и население мира?'},intro:{ja:'航海技術、国家競争、銀、植民地化、疫病、作物交換を一つの世界システムとして見ます。',ru:'Навигация, конкуренция государств, серебро, колонизация, болезни и обмен культурами образуют одну систему.'},chapters:[]}
};
let topicsView=null,topicOpen=null,mediaObserver=null;
function patchHomeTitle(){const h=$('#homeTitle');if(!h)return;if(ja())h.innerHTML='<span>世界史を、</span><span>つながりで理解する</span>'}
function patchNav(){const nav=$('#bottomNav');if(!nav||nav.dataset.v7)return;nav.dataset.v7='1';const map=nav.querySelector('[data-route="map"]'),profile=nav.querySelector('[data-route="profile"]'),lib=nav.querySelector('[data-route="library"]');if(map)map.hidden=true;if(profile)profile.hidden=true;if(lib){const t=lib.querySelector('span');if(t){t.id='';t.textContent=ja()?'INDEX':'УКАЗАТЕЛЬ'}}const b=document.createElement('button');b.className='nav-button v7-topics-nav';b.type='button';b.dataset.v7Topics='1';b.innerHTML='<svg viewBox="0 0 24 24"><path d="M5 5h6v6H5zM13 5h6v6h-6zM5 13h6v6H5zM13 13h6v6h-6z"/></svg><span>'+(ja()?'TOPICS':'ТЕМЫ')+'</span>';if(lib)nav.insertBefore(b,lib);else nav.appendChild(b)}
function renderDrawer(){const ov=$('#menuOverlay'),sheet=ov?.querySelector('.menu-sheet');if(!ov||!sheet)return;ov.classList.add('v7-drawer-overlay');sheet.classList.add('v7-drawer');sheet.innerHTML=`<div class="v7-drawer-head"><div class="wordmark">CHRONOS</div><button type="button" class="v7-drawer-close" data-action="close-overlay" aria-label="${ja()?'閉じる':'Закрыть'}">×</button></div><div class="v7-drawer-body"><button class="v7-menu-row" data-route="map"><span class="v7-menu-icon">◎</span><span><strong>${ja()?'理解マップ':'Карта понимания'}</strong><small>${ja()?'自分の理解の広がりを見る':'Посмотреть, что уже связано'}</small></span><b>›</b></button><button class="v7-menu-row" data-action="guide"><span class="v7-menu-icon">?</span><span><strong>${ja()?'CHRONOSの使い方':'Как пользоваться CHRONOS'}</strong><small>${ja()?'迷ったときに30秒で確認':'Короткая подсказка по использованию'}</small></span><b>›</b></button><div class="v7-menu-section"><small>${ja()?'言語':'Язык'}</small><div class="v7-choice-pair"><button data-lang-choice="ja">日本語</button><button data-lang-choice="ru">Русский</button></div></div><div class="v7-menu-section"><small>${ja()?'表示':'Оформление'}</small><div class="v7-choice-pair"><button data-theme-choice="dark">Dark Museum</button><button data-theme-choice="light">Ivory Gallery</button></div></div><div class="v7-menu-section"><small>${ja()?'学習の深さ':'Глубина изучения'}</small><div class="v7-choice-pair"><button data-depth-choice="auto">${ja()?'自動':'Авто'}</button><button data-depth-choice="expert">${ja()?'専門':'Эксперт'}</button></div></div><button class="v7-menu-row v7-settings-link" data-route="profile"><span class="v7-menu-icon">⚙</span><span><strong>${ja()?'詳細設定':'Настройки'}</strong><small>${ja()?'設定画面を開く':'Открыть все настройки'}</small></span><b>›</b></button></div>`;syncDrawerChoices();let sx=0,sy=0;sheet.ontouchstart=e=>{const t=e.touches[0];sx=t.clientX;sy=t.clientY};sheet.ontouchend=e=>{const t=e.changedTouches[0];if(t.clientX-sx>65&&Math.abs(t.clientY-sy)<70)ov.hidden=true}}
function syncDrawerChoices(){const ov=$('#menuOverlay');if(!ov)return;ov.querySelectorAll('[data-lang-choice]').forEach(b=>b.classList.toggle('active',b.dataset.langChoice===lang()));const th=document.documentElement.dataset.theme||localStorage.getItem('chronos-theme')||'dark';ov.querySelectorAll('[data-theme-choice]').forEach(b=>b.classList.toggle('active',b.dataset.themeChoice===th));const d=localStorage.getItem('chronos-depth')||'auto';ov.querySelectorAll('[data-depth-choice]').forEach(b=>b.classList.toggle('active',b.dataset.depthChoice===d))}
function titleForIndex(){const t=$('#libraryTitle'),p=$('#libraryCopy');if(t)t.textContent=ja()?'人類史の年表':'Хронология человечества';if(p)p.textContent=ja()?'古い出来事から順に、人類の歩みをたどります。':'История человечества — от древнейших событий к современности.'}
let idxCat='all',idxRegion='all';
const regionDefs=[['all',{ja:'すべて',ru:'Все'}],['africa',{ja:'アフリカ',ru:'Африка'}],['westasia',{ja:'西アジア',ru:'Западная Азия'}],['europe',{ja:'ヨーロッパ',ru:'Европа'}],['eastasia',{ja:'東アジア',ru:'Восточная Азия'}],['southasia',{ja:'南アジア',ru:'Южная Азия'}],['americas',{ja:'アメリカ大陸',ru:'Америки'}]];
function regionKey(r=''){if(/Africa/.test(r))return'africa';if(/Mesopotamia|Arabia|West Asia|Levant/.test(r))return'westasia';if(/Europe|Mediterranean|Britain|Atlantic/.test(r))return'europe';if(/East Asia|China|Japan/.test(r))return'eastasia';if(/South Asia|India/.test(r))return'southasia';if(/America|Mesoamerica/.test(r))return'americas';return'other'}
function ensureIndexControls(){const old=$('#libraryFilters');if(old)old.hidden=true;const grid=$('#libraryGrid');if(!grid)return null;let c=$('#v7IndexControls');if(!c){c=document.createElement('div');c.id='v7IndexControls';c.className='v7-index-controls';grid.parentNode.insertBefore(c,grid)}const cats=[['all',ja()?'すべて':'Все'],['human',ja()?'人類・環境':'Люди и среда'],['power',ja()?'政治・帝国':'Политика'],['ideas',ja()?'思想・宗教':'Идеи и религии'],['tech',ja()?'技術・経済':'Технологии']];c.innerHTML=`<button class="v7-filter-toggle" type="button"><span>${ja()?'絞り込み':'Фильтры'}</span><b>＋</b></button><div class="v7-filter-panel" hidden><small>${ja()?'分野':'Область'}</small><div class="v7-filter-chips">${cats.map(([k,n])=>`<button data-v7-cat="${k}" class="${idxCat===k?'active':''}">${n}</button>`).join('')}</div><small>${ja()?'地域':'Регион'}</small><div class="v7-filter-chips">${regionDefs.map(([k,n])=>`<button data-v7-region="${k}" class="${idxRegion===k?'active':''}">${l(n)}</button>`).join('')}</div></div>`;c.querySelector('.v7-filter-toggle').onclick=()=>{const p=c.querySelector('.v7-filter-panel');p.hidden=!p.hidden;c.querySelector('.v7-filter-toggle b').textContent=p.hidden?'＋':'−'};return c}
function renderIndex(){if((location.hash||'#home')!=='#library')return;titleForIndex();ensureIndexControls();const grid=$('#libraryGrid');if(!grid)return;grid.className='v7-index';const visited=new Set(read('chronos-visited')),mastered=new Set(read('chronos-mastered'));const arr=[...(D.TIMEPOINTS||[])].sort((a,b)=>(+a.year||0)-(+b.year||0)).filter(p=>(idxCat==='all'||p.cat===idxCat)&&(idxRegion==='all'||regionKey(p.region)===idxRegion));grid.innerHTML=arr.map((p,i)=>{const event=Object.entries(D.EVENTS||{}).find(([,e])=>e?.point===p.id)?.[0]||p.id;const seen=visited.has(p.id),medal=mastered.has(p.id)||mastered.has(event);return`<button class="v7-index-row ${seen?'seen':''}" data-event="${esc(event)}"><span class="v7-index-time"><i></i><small>${esc(l(p.label))}</small></span><span class="v7-index-media"><img alt="${esc(l(p.title))}" loading="lazy" data-media-id="${esc(event)}" data-media-title="${esc(l(p.title))}"></span><span class="v7-index-copy"><strong>${esc(l(p.title))}${medal?'<i class="v7-medal" aria-label="'+(ja()?'自分の言葉で説明できる':'Можно объяснить своими словами')+'"></i>':''}</strong><span>${esc(summary(p))}</span></span></button>`}).join('');bindMedia(grid);const c=$('#v7IndexControls');if(c){c.querySelectorAll('[data-v7-cat]').forEach(b=>b.onclick=()=>{idxCat=b.dataset.v7Cat;renderIndex()});c.querySelectorAll('[data-v7-region]').forEach(b=>b.onclick=()=>{idxRegion=b.dataset.v7Region;renderIndex()})}}
function summary(p){const e=Object.values(D.EVENTS||{}).find(x=>x?.point===p.id);const s=l(e?.lead||'');if(s)return s.replace(/\s+/g,' ').slice(0,92);const m={human:{ja:'人間の暮らしと環境の関係が変化した節目。',ru:'Поворотный момент во взаимодействии людей и среды.'},power:{ja:'国家・権力・制度のかたちが変化した節目。',ru:'Поворотный момент в истории власти, государств и институтов.'},ideas:{ja:'宗教・思想・文化の見方が広がった節目。',ru:'Поворотный момент в истории идей, религии и культуры.'},tech:{ja:'技術・交易・経済のつながりが変化した節目。',ru:'Поворотный момент в технологиях, торговле и экономике.'}};return l(m[p.cat]||m.human)}
function bindMedia(root){const imgs=[...root.querySelectorAll('img[data-media-id]')];if(!('IntersectionObserver'in window)){imgs.slice(0,10).forEach(resolveImg);return}mediaObserver?.disconnect();mediaObserver=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){resolveImg(e.target);mediaObserver.unobserve(e.target)}}),{rootMargin:'450px 0px'});imgs.forEach(im=>mediaObserver.observe(im))}
async function resolveImg(im){if(im.dataset.loaded)return;im.dataset.loaded='1';const id=im.dataset.mediaId,title=im.dataset.mediaTitle;try{const hit=await M?.resolve?.(id,title);if(hit?.url){im.src=hit.url;return}}catch{}im.closest('.v7-index-media,.v7-topic-media')?.classList.add('fallback')}
function ensureTopicsView(){if(topicsView)return topicsView;topicsView=document.createElement('section');topicsView.id='v7TopicsView';topicsView.className='v7-topics-view';topicsView.hidden=true;$('#app main')?.appendChild(topicsView);return topicsView}
function topicCard(id,t,featured=false){return`<button class="v7-topic-card ${featured?'featured':''}" data-v7-topic="${id}"><span class="v7-topic-media"><img data-media-id="${id}" data-media-title="${esc(l(t.title))}" alt="${esc(l(t.title))}" loading="lazy"></span><span class="v7-topic-shade"></span><span class="v7-topic-copy"><small>${esc(l(t.period))}</small><strong>${esc(l(t.title))}</strong><em>${esc(l(t.sub))}</em>${featured?`<p>${esc(l(t.hook))}</p>`:''}</span></button>`}
function renderTopics(id=null){const v=ensureTopicsView();topicOpen=id;if(!id){const keys=['viking','egypt','french','silk','mongol','crusades','exploration'];v.innerHTML=`<div class="page-pad top-space v7-topics-page"><div class="eyebrow">TOPICS</div><h1 class="page-title">${ja()?'テーマから旅する':'Путешествовать по темам'}</h1><p class="page-copy">${ja()?'時代や地域をまたいで、ひとつのテーマから歴史のつながりをたどります。':'Следуйте по связям истории, начиная с темы, а не только с даты или места.'}</p><div class="v7-topic-grid">${keys.map((k,i)=>topicCard(k,topicData[k],i===0)).join('')}</div></div>`;bindMedia(v)}else{const t=topicData[id];v.innerHTML=`<div class="page-pad top-space v7-topic-detail"><button class="text-link v7-topic-back" data-v7-topic-back>← ${ja()?'テーマ一覧':'Все темы'}</button><div class="v7-topic-hero"><span class="v7-topic-media"><img data-media-id="${id}" data-media-title="${esc(l(t.title))}" alt="${esc(l(t.title))}"></span><span class="v7-topic-shade"></span><div class="v7-topic-hero-copy"><small>${esc(l(t.period))}</small><h1>${esc(l(t.title))}</h1><strong>${esc(l(t.sub))}</strong><p>${esc(l(t.hook))}</p></div></div><p class="v7-topic-intro">${esc(l(t.intro))}</p>${t.chapters.length?`<div class="v7-topic-chapters">${t.chapters.map((c,i)=>`<article><button data-v7-chapter="${i}"><small>${String(i+1).padStart(2,'0')}</small><strong>${esc(ja()?c[0]:c[1])}</strong><b>＋</b></button><div hidden><p>${esc(ja()?c[2]:c[3])}</p></div></article>`).join('')}</div>`:`<div class="v7-topic-coming">${ja()?'このテーマの章を編集中です。':'Разделы этой темы дополняются.'}</div>`}</div>`;bindMedia(v)}return v}
function openTopics(id=null){const v=renderTopics(id);$$('.screen').forEach(s=>s.style.display='none');v.hidden=false;$('#topbar').hidden=false;$$('#bottomNav .nav-button').forEach(b=>b.classList.remove('active'));$('.v7-topics-nav')?.classList.add('active');scrollTo(0,0)}
function closeTopics(){if(!topicsView||topicsView.hidden)return;topicsView.hidden=true;$$('.screen').forEach(s=>s.style.removeProperty('display'));topicOpen=null}
function firstJourney(){if(localStorage.getItem('chronos-first-journey-v7'))return;const ov=document.createElement('div');ov.className='v7-first-journey';ov.innerHTML=`<div class="v7-first-inner"><div class="wordmark">CHRONOS</div><div class="eyebrow">${ja()?'FIRST JOURNEY':'ПЕРВОЕ ПУТЕШЕСТВИЕ'}</div><h1>${ja()?'最初の旅を選ぶ':'Выберите первое путешествие'}</h1><p>${ja()?'説明を読む必要はありません。気になるものをひとつ選んでください。':'Не нужно читать инструкцию — просто выберите то, что вас заинтересовало.'}</p><div class="v7-first-grid">${topicCard('viking',topicData.viking,true)}${topicCard('egypt',topicData.egypt)}${topicCard('french',topicData.french)}</div></div>`;document.body.appendChild(ov);bindMedia(ov);document.documentElement.classList.add('v7-first-open');ov.addEventListener('click',e=>{const b=e.target.closest('[data-v7-topic]');if(!b)return;localStorage.setItem('chronos-first-journey-v7','done');ov.remove();document.documentElement.classList.remove('v7-first-open');openTopics(b.dataset.v7Topic)})}
function onLang(){patchHomeTitle();patchNavLabels();renderDrawer();if((location.hash||'#home')==='#library')setTimeout(renderIndex,0);if(topicsView&&!topicsView.hidden)renderTopics(topicOpen)}
function patchNavLabels(){const lib=$('#bottomNav [data-route="library"] span');if(lib)lib.textContent=ja()?'INDEX':'УКАЗАТЕЛЬ';const tp=$('.v7-topics-nav span');if(tp)tp.textContent=ja()?'TOPICS':'ТЕМЫ'}
document.addEventListener('click',e=>{const top=e.target.closest('[data-v7-topics]');if(top){e.preventDefault();openTopics();return}const tc=e.target.closest('[data-v7-topic]');if(tc&&!e.target.closest('.v7-first-journey')){openTopics(tc.dataset.v7Topic);return}if(e.target.closest('[data-v7-topic-back]')){renderTopics();return}const ch=e.target.closest('[data-v7-chapter]');if(ch){const body=ch.parentElement.querySelector('div');body.hidden=!body.hidden;ch.querySelector('b').textContent=body.hidden?'＋':'−';return}if(e.target.closest('#menuOverlay [data-lang-choice],#menuOverlay [data-theme-choice],#menuOverlay [data-depth-choice]'))setTimeout(syncDrawerChoices,0)});
addEventListener('hashchange',()=>{closeTopics();setTimeout(()=>{if(location.hash==='#library')renderIndex()},10)});
const mo=new MutationObserver(ms=>{if(ms.some(m=>m.attributeName==='lang'||m.attributeName==='data-lang'))onLang()});mo.observe(document.documentElement,{attributes:true,attributeFilter:['lang','data-lang']});
function init(){patchHomeTitle();patchNav();renderDrawer();if(location.hash==='#library')setTimeout(renderIndex,60);setTimeout(firstJourney,520)}
init();
})();