(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={index:null,topic:null,current:null,visited:new Set(JSON.parse(localStorage.getItem('chronos-preview-visited')||'[]')),mission:new Set(JSON.parse(localStorage.getItem('chronos-preview-mission')||'[]'))};
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
async function j(u){const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error(u);return r.json()}
async function ensure(){if(state.index)return;[state.index,state.topic]=await Promise.all([j('../content-v1/index.json'),j('../content-v1/topics/viking-age.json')])}
function meta(id){return state.index.pages.find(x=>x.id===id)}
function path(id){const m=meta(id);return m?'../content-v1/'+m.path.replace(/^\.\//,''):null}
function save(){localStorage.setItem('chronos-preview-visited',JSON.stringify([...state.visited]));localStorage.setItem('chronos-preview-mission',JSON.stringify([...state.mission]))}
function view(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v+'View'));$$('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));scrollTo({top:0,behavior:'instant'});if(v==='explore')renderExplore();if(v==='mission')renderMission()}
async function renderExplore(){await ensure();const root=$('#exploreRoot'),done=state.topic.route.filter(id=>state.visited.has(id)).length;root.innerHTML=`<section class="topic-card"><small>FEATURED WORLD</small><h2>${esc(state.topic.title.ja)}</h2><p>${esc(state.topic.hero.hook.ja)}</p><div class="progress"><i style="width:${done/state.topic.route.length*100}%"></i></div><small>${done} / ${state.topic.route.length} 探索済み</small></section><div class="topic-list">${state.topic.route.map((id,i)=>`<button data-page="${id}" class="${state.visited.has(id)?'visited':''}"><small>${String(i+1).padStart(2,'0')}</small><strong>${esc(meta(id).title.ja)}</strong><span>→</span></button>`).join('')}</div>`}
async function openPage(id){await ensure();const p=await j(path(id));state.current=p;state.visited.add(id);if(['viking-02-everyday-life','viking-03-why-sea','viking-05-raids-and-trade'].includes(id))state.mission.add(id);save();const root=$('#exploreRoot');root.innerHTML=`<button class="back" data-view="explore">← ヴァイキング時代へ戻る</button><article class="article"><small class="eyebrow">QUESTION</small><h2>${esc(p.title.ja)}</h2><p>${esc(p.question.ja)}</p><section class="answer"><small>結論からいうと</small><p>${esc(p.answer.ja)}</p></section><div class="story">${(p.story.ja||[]).map(x=>`<p>${esc(x)}</p>`).join('')}</div>${p.evidence?`<section class="evidence"><h3>なぜそう言える？</h3><ul>${(p.evidence.ja||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`:''}${p.so_what?`<section class="evidence"><h3>だから何が重要？</h3><p>${esc(p.so_what.ja)}</p></section>`:''}</article>`;renderMission(false);scrollTo({top:0,behavior:'instant'})}
function clues(){return[{id:'viking-02-everyday-life',t:'北欧社会の暮らしを知る'},{id:'viking-03-why-sea',t:'なぜ海へ出たのかを調べる'},{id:'viking-05-raids-and-trade',t:'略奪と交易の関係を見る'}]}
function renderMission(scroll=true){const root=$('#missionRoot'),items=clues(),done=items.filter(x=>state.mission.has(x.id)).length,unlock=done===items.length;root.innerHTML=`<section class="mission-card"><div class="mission-top"><small>MISSION 01 · DISCOVER</small><span>${done} / 3</span></div><h2>なぜ北欧の人々は海へ出て、広い世界とつながったのか？</h2><p>3つの手がかりをCHRONOSの中から集めてください。答えは先に表示しません。</p><div class="progress"><i style="width:${done/3*100}%"></i></div><div class="clues">${items.map((x,i)=>`<button data-page="${x.id}" class="${state.mission.has(x.id)?'done':''}"><small>手がかり ${i+1}</small><strong>${x.t}</strong><span>${state.mission.has(x.id)?'調査済み':'調べる'} →</span></button>`).join('')}</div></section><section class="final ${unlock?'':'locked'}"><small>FINAL TEST</small><h2>${unlock?'ヴァイキング時代に北欧の人々が海へ出た理由を、複数の要因をつないで説明してください。':'3つの手がかりを調べると解放されます'}</h2>${unlock?`<textarea id="finalAnswer" rows="6" placeholder="自分の言葉で説明する"></textarea><button class="submit" id="submitFinal">答えを確かめる</button><div class="feedback" id="feedback"></div>`:''}</section>`;if(scroll)scrollTo({top:0,behavior:'instant'})}
function grade(){const a=$('#finalAnswer')?.value.trim()||'',f=$('#feedback');if(!f)return;const strong=a.length>=70&&/(船|海|交易|農|人口|技術)/.test(a);f.textContent=strong?'MISSION COMPLETE — ひとつの原因ではなく、複数の条件をつないで考えられています。':'もう少し調べた内容をつないでみましょう。原因を2つ以上入れて説明してみてください。'}
document.addEventListener('click',e=>{const v=e.target.closest('[data-view]');if(v){e.preventDefault();view(v.dataset.view);return}const p=e.target.closest('[data-page]');if(p){e.preventDefault();view('explore');openPage(p.dataset.page).catch(console.error);return}if(e.target.closest('#submitFinal'))grade()});
ensure().then(()=>{renderExplore();renderMission(false)}).catch(console.error);
})();